In [89]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model  import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [90]:
iris_df=pd.read_excel("Iris data.xls")
iris_df.head()

sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [91]:
iris_df.describe()

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [92]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length    150 non-null float64
sepal width     150 non-null float64
petal length    150 non-null float64
petal width     150 non-null float64
iris            150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [93]:
iris_df.isna().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
iris            0
dtype: int64

In [94]:
iris_df.shape

(150, 5)

In [95]:
le=preprocessing.LabelEncoder()

In [96]:
iris_df["iris"]=le.fit_transform(iris_df["iris"])
iris_df["iris"].value_counts()

2    50
1    50
0    50
Name: iris, dtype: int64

In [97]:
iris=iris_df["iris"]
iris.head()

0    0
1    0
2    0
3    0
4    0
Name: iris, dtype: int64

In [98]:
iris_df.drop(["iris"],axis=1,inplace=True)
iris_df.head()

sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [99]:
scaler = MinMaxScaler()

norm_iris= pd.DataFrame(scaler.fit_transform(iris_df))
norm_iris.head(3)

0         1         2         3
0  0.222222  0.625000  0.067797  0.041667
1  0.166667  0.416667  0.067797  0.041667
2  0.111111  0.500000  0.050847  0.041667

In [100]:
norm_iris["iris"]=iris
norm_iris.head()

0         1         2         3  iris
0  0.222222  0.625000  0.067797  0.041667     0
1  0.166667  0.416667  0.067797  0.041667     0
2  0.111111  0.500000  0.050847  0.041667     0
3  0.083333  0.458333  0.084746  0.041667     0
4  0.194444  0.666667  0.067797  0.041667     0

In [101]:
norm_iris.columns=["sepal length","sepal width","petal length","petal width","iris"]
norm_iris.head()

sepal length  sepal width  petal length  petal width  iris
0      0.222222     0.625000      0.067797     0.041667     0
1      0.166667     0.416667      0.067797     0.041667     0
2      0.111111     0.500000      0.050847     0.041667     0
3      0.083333     0.458333      0.084746     0.041667     0
4      0.194444     0.666667      0.067797     0.041667     0

In [102]:
norm_iris.corr()

sepal length  sepal width  petal length  petal width      iris
sepal length      1.000000    -0.109369      0.871754     0.817954  0.782561
sepal width      -0.109369     1.000000     -0.420516    -0.356544 -0.419446
petal length      0.871754    -0.420516      1.000000     0.962757  0.949043
petal width       0.817954    -0.356544      0.962757     1.000000  0.956464
iris              0.782561    -0.419446      0.949043     0.956464  1.000000

In [103]:
feature=norm_iris.loc[:,["sepal width","petal length"]]
dependent=norm_iris.loc[:,"iris"]
iris_train,iris_test,label_train,label_test=train_test_split(feature,dependent,test_size=0.40,random_state=0)
display(iris_train.shape)
display(iris_test.shape)

(90, 2)

(60, 2)

In [104]:
mod=LogisticRegression()
mod.fit(iris_train,label_train)


# predicting the test set results

y_pred=mod.predict(iris_test)


In [105]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 1, 0, 2, 2, 0, 2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2], dtype=int64)

In [106]:
from sklearn.metrics import accuracy_score

In [107]:
cm=confusion_matrix(label_test,y_pred)
display(cm)

array([[16,  0,  0],
       [ 0,  9, 14],
       [ 0,  2, 19]], dtype=int64)

In [108]:
accuracy_score(label_test,y_pred)

0.7333333333333333

In [109]:
print("train accuracy")
display(mod.score(iris_train,label_train))


print("test accuracy")
display(mod.score(iris_test,label_test))

train accuracy


0.8333333333333334

test accuracy


0.7333333333333333

In [110]:
train_prediction=mod.predict(iris_train)
test_prediction=mod.predict(iris_test)
train_conf_matrix=confusion_matrix(label_train,train_prediction)
test_conf_matrix=confusion_matrix(label_test,test_prediction)

In [111]:
pd.DataFrame(train_conf_matrix,columns=mod.classes_,index=mod.classes_)

0   1   2
0  34   0   0
1   0  12  15
2   0   0  29

In [112]:
pd.DataFrame(test_conf_matrix,columns=mod.classes_,index=mod.classes_)

0  1   2
0  16  0   0
1   0  9  14
2   0  2  19

In [113]:
print(classification_report(label_train,train_prediction))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        34
          1       1.00      0.44      0.62        27
          2       0.66      1.00      0.79        29

avg / total       0.89      0.83      0.82        90



In [114]:
print(classification_report(label_test,test_prediction))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.82      0.39      0.53        23
          2       0.58      0.90      0.70        21

avg / total       0.78      0.73      0.72        60



In [115]:
# decision tree algorithm 

model=DecisionTreeClassifier()

model.fit(iris_train,label_train)
print("train accuracy")
display(model.score(iris_train,label_train))

print("test accuracy")
display(model.score(iris_test,label_test))

train accuracy


1.0

test accuracy


0.9

In [116]:
y_pred=model.predict(iris_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2], dtype=int64)

In [117]:
cm=confusion_matrix(label_test,y_pred)
display(cm)

array([[16,  0,  0],
       [ 0, 21,  2],
       [ 0,  4, 17]], dtype=int64)

In [118]:
# k nearest algorithm    


kmodel=KNeighborsClassifier(n_neighbors=3,metric="euclidean")


kmodel.fit(iris_train,label_train)
print("train accuracy")
display(kmodel.score(iris_train,label_train))

print("test accuracy")
display(kmodel.score(iris_test,label_test))

train accuracy


0.9666666666666667

test accuracy


0.9333333333333333

In [119]:
y_pred=kmodel.predict(iris_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2], dtype=int64)

In [120]:
cm=confusion_matrix(label_test,y_pred)
display(cm)

array([[16,  0,  0],
       [ 0, 22,  1],
       [ 0,  3, 18]], dtype=int64)

In [121]:
smodel=SVC(kernel="rbf")
smodel.fit(iris_train,label_train)
print("train accuracy")
display(smodel.score(iris_train,label_train))

print("test accuracy")
display(smodel.score(iris_test,label_test))

train accuracy


0.9444444444444444

test accuracy


0.8333333333333334

In [122]:
y_pred=kmodel.predict(iris_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2], dtype=int64)

In [123]:
cm=confusion_matrix(label_test,y_pred)
display(cm)

array([[16,  0,  0],
       [ 0, 22,  1],
       [ 0,  3, 18]], dtype=int64)

In [124]:
#ensemble techniques KFold technique for logistic regression algorithm

from sklearn.model_selection import KFold
k_fold=KFold(n_splits=5,shuffle=False,random_state=100)
train_acc=[]
test_acc=[]
X=iris_train
y=label_train
for i,(train,test) in enumerate(k_fold.split(X,y)):
    lmodel=LogisticRegression()
    a=X.iloc[train]
    b=y.iloc[train]
    lmodel.fit(a,b)
    print(lmodel.score(a,b))
    print(lmodel.score(a,b))
    train_acc.append(lmodel.score(a,b))
    test_acc.append(lmodel.score(a,b))
    print("*********************************************************")
    

0.7916666666666666
0.7916666666666666
*********************************************************
0.8888888888888888
0.8888888888888888
*********************************************************
0.8055555555555556
0.8055555555555556
*********************************************************
0.8333333333333334
0.8333333333333334
*********************************************************
0.7777777777777778
0.7777777777777778
*********************************************************


In [125]:
print(np.max(train_acc))
print(np.max(test_acc))

0.8888888888888888
0.8888888888888888


In [126]:
## RandomForestClassifier

from sklearn.ensemble import RandomForestClassifier
rmodel=RandomForestClassifier(n_estimators=10,min_samples_split=20,min_impurity_decrease=0.1)
rmodel.fit(iris_train,label_train)
print("train accuracy")
display(rmodel.score(iris_train,label_train))

print("test accuracy")
display(rmodel.score(iris_test,label_test))

train accuracy


0.9777777777777777

test accuracy


0.8666666666666667

In [127]:
from sklearn.ensemble import AdaBoostClassifier
amodel=AdaBoostClassifier(n_estimators=10)
amodel.fit(iris_train,label_train)
print("train accuracy")
display(amodel.score(iris_train,label_train))

print("test accuracy")
display(amodel.score(iris_test,label_test))

train accuracy


0.9777777777777777

test accuracy


0.95

In [128]:
#ensemble techniques KFold technique for SVM algorithm


from sklearn.model_selection import KFold
k_fold=KFold(n_splits=5,shuffle=False,random_state=100)
train_acc=[]
test_acc=[]
X=iris_train
y=label_train
for i,(train,test) in enumerate(k_fold.split(X,y)):
    s1model=SVC(kernel="rbf")
    a=X.iloc[train]
    b=y.iloc[train]
    s1model.fit(a,b)
    print(s1model.score(a,b))
    print(s1model.score(a,b))
    train_acc.append(s1model.score(a,b))
    test_acc.append(s1model.score(a,b))
    print("*********************************************************")

0.9444444444444444
0.9444444444444444
*********************************************************
0.9166666666666666
0.9166666666666666
*********************************************************
0.9305555555555556
0.9305555555555556
*********************************************************
0.9305555555555556
0.9305555555555556
*********************************************************
0.9305555555555556
0.9305555555555556
*********************************************************


In [129]:
print(np.max(train_acc))
print(np.max(test_acc))

0.9444444444444444
0.9444444444444444


In [130]:
# ensemble technique kfold for knn algorithm 


from sklearn.model_selection import KFold
k_fold=KFold(n_splits=5,shuffle=False,random_state=100)
km=[1,2,3,4,5]
avg_train=[]
avg_test=[]
X=iris_train
y=label_train
for k in km:
    train_acc=[]
    test_acc=[]
    for i,(train,test) in enumerate(k_fold.split(X,y)):
        kmodel=KNeighborsClassifier(n_neighbors=k,metric="euclidean")
        kmodel.fit(X.iloc[train],y.iloc[train])
        print(model.score(X.iloc[train],y.iloc[train]))
        print(model.score(X.iloc[test],y.iloc[test]))
        train_acc.append(model.score(X.iloc[train],y.iloc[train]))
        test_acc.append(model.score(X.iloc[test],y.iloc[test]))
        print("*********************************************************")
    avg_train.append(np.mean(train_acc))
    avg_test.append(np.mean(test_acc))

1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
*********************************************************
1.0
1.0
**

In [131]:
print(np.max(avg_train))
print(np.max(avg_test))

1.0
1.0
